export const SITE = {
  name: 'Greenfield Institute',
  fullName: 'Greenfield Institute of Computer Education and Applied Sciences',
  shortName: 'GICEAS',
  tagline: 'Constituent College of Meridian State University, Surat',
  university: 'Meridian State University',
  universityUrl: 'https://meridianuniversity.ac.in',
  address: '123 College Road, Near City Park, Sample Nagar, Surat – 395007, Gujarat, India.',
  phones: { admin: '9999900001', institute: ['9999900002', '9999900003'], principal: '9999900004', whatsapp: '9999900005' },
  email: 'info@greenfield.ac.in',
  social: {
    facebook: 'https://www.facebook.com/GreenfieldInstitute/',
    instagram: 'https://www.instagram.com/greenfield_institute/',
    youtube: 'https://www.youtube.com/c/greenfieldedu',
  },
}

export const NAV = [
  {
    label: 'Home', href: '/',
  },
  {
    label: 'About Us', href: '/about',
    children: [
      { label: 'GICEAS – Constituent College', href: '/about' },
      { label: 'History', href: '/about/history' },
      { label: 'Vision, Mission & Values', href: '/about/vision-mission' },
      { label: "Chairman's Message", href: '/about/chairman-message' },
      { label: "Principal's Message", href: '/about/principal-message' },
      { label: 'Working Committee', href: '/about/working-committee' },
      { label: 'Donors', href: '/about/donors' },
      { label: 'Past Principals', href: '/about/principals' },
      { label: 'Awards & Recognitions', href: '/about/awards' },
    ],
  },
  {
    label: 'Academic', href: '/academic',
    children: [
      { label: 'Courses Offered', href: '/academic/courses' },
      { label: 'Fees Structure', href: '/academic/fees' },
      { label: 'SU Syllabus', href: '/academic/syllabus' },
      { label: 'Accreditation', href: '/academic/accreditation' },
      { label: 'AQAR Report', href: '/academic/aqar' },
      { label: 'IQAC Committee', href: '/academic/iqac' },
      { label: 'AISHE', href: '/academic/aishe' },
      { label: 'UGC Notification', href: '/academic/ugc' },
    ],
  },
  {
    label: 'Departments', href: '/departments',
    children: [
      { label: 'Computer Science', href: '/departments/computer-science' },
      { label: 'Microbiology', href: '/departments/microbiology' },
      { label: 'Biotechnology', href: '/departments/biotechnology' },
      { label: 'Environmental Science', href: '/departments/environmental-science' },
      { label: 'Chemistry', href: '/departments/chemistry' },
      { label: 'Allied Sciences', href: '/departments/allied' },
      { label: 'Administration', href: '/departments/admin' },
      { label: 'Library', href: '/departments/library' },
    ],
  },
  {
    label: 'Campus', href: '/campus',
    children: [
      { label: 'Laboratory', href: '/campus#laboratory' },
      { label: 'Library', href: '/campus#library' },
      { label: 'Seminar Hall', href: '/campus#seminar-hall' },
      { label: 'Playground', href: '/campus#playground' },
      { label: 'Hostel', href: '/campus#hostel' },
      { label: 'Canteen', href: '/campus#canteen' },
      { label: 'Sports', href: '/campus#sports' },
      { label: 'NCC Office', href: '/campus#ncc' },
    ],
  },
  {
    label: 'Students Zone', href: '/students',
    children: [
      { label: 'Academic Calendar', href: '/students/academic-calendar' },
      { label: 'Previous Question Papers', href: '/students/question-papers' },
      { label: 'E-Magazine', href: '/students/e-magazine' },
      { label: 'Scholarship & Freeship', href: '/students/scholarship' },
      { label: 'Anti Ragging Committee', href: '/students/anti-ragging' },
      { label: 'Gender Sensitization Cell', href: '/students/gender-cell' },
      { label: 'Code of Conduct', href: '/students/code-of-conduct' },
      { label: 'Result', href: '/result' },
      { label: 'Admission Forms', href: '/students/forms' },
      { label: 'Alumni Portal', href: 'https://www.alumni.greenfield.ac.in', external: true },
      { label: 'Fees Payment', href: 'https://fees.greenfield.ac.in', external: true },
    ],
  },
  {
    label: 'Activities', href: '/activities',
    children: [
      { label: 'Cells & Committees', href: '/activities/cells-committees' },
      { label: 'NSS', href: '/activities/nss' },
      { label: 'NCC', href: '/activities/ncc' },
      { label: 'Red Cross', href: '/activities/red-cross' },
      { label: 'Cultural', href: '/activities/cultural' },
      { label: 'Sports Activities', href: '/activities/sports' },
      { label: 'Maitri Setu', href: '/activities/maitri-setu' },
      { label: 'Educational Tour', href: '/activities/educational-tour' },
    ],
  },
  {
    label: 'Placement', href: '/placement',
    children: [
      { label: 'Training & Placement Cell', href: '/placement' },
      { label: 'CS Placement', href: '/placement/computer-science' },
      { label: 'Microbiology Placement', href: '/placement/microbiology' },
      { label: 'Biotechnology Placement', href: '/placement/biotechnology' },
      { label: 'Environmental Science', href: '/placement/environmental-science' },
      { label: 'Chemistry Placement', href: '/placement/chemistry' },
      { label: 'Placement Events', href: '/placement/events' },
    ],
  },
  {
    label: 'Research', href: '/research',
    children: [
      { label: 'Research Facility', href: '/research' },
      { label: 'Research Activities', href: '/research/activities' },
      { label: 'Papers by Faculties', href: '/research/papers' },
      { label: 'Research Guides', href: '/research/guides' },
      { label: 'Research Scholars', href: '/research/scholars' },
    ],
  },
  {
    label: 'Media', href: '/media',
    children: [
      { label: 'Photo Gallery', href: '/gallery' },
      { label: 'Video Gallery', href: '/media/videos' },
      { label: 'News & Activities', href: '/news' },
      { label: 'Awards & Recognitions', href: '/about/awards' },
    ],
  },
  {
    label: 'Ranking', href: '/academic/nirf',
    children: [
      { label: 'NIRF', href: '/academic/nirf' },
      { label: 'GSIRF', href: '/academic/gsirf' },
    ],
  },
  {
    label: 'ICC', href: '/icc',
    children: [
      { label: 'About ICC', href: '/icc' },
      { label: 'Members', href: '/icc/members' },
      { label: 'Objectives & Visions', href: '/icc/objectives' },
      { label: 'Plan of Actions', href: '/icc/plan-of-actions' },
      { label: 'Procedure', href: '/icc/procedure' },
      { label: 'Definition of Sexual Harassment', href: '/icc/definition' },
      { label: 'Disciplinary Mechanism', href: '/icc/disciplinary-mechanism' },
    ],
  },
]

export const DEPARTMENTS = [
  {
    slug: 'computer-science',
    name: 'Computer Science',
    color: '#3b82f6',
    bg: 'bg-blue-50',
    border: 'border-blue-200',
    icon: '💻',
    programs: ['B.Sc. (CS)', 'M.Sc. (CS)', 'BCA', 'MCA'],
    hod: 'Dr. [Name]',
    about: 'The Department of Computer Science offers comprehensive programs in computing, software engineering, data science, and IT. Equipped with modern labs, students gain both theoretical knowledge and practical skills to thrive in the technology industry.',
    labs: ['Programming Lab', 'Networking Lab', 'Project Lab'],
    faculty: 8,
  },
  {
    slug: 'microbiology',
    name: 'Microbiology',
    color: '#22c55e',
    bg: 'bg-green-50',
    border: 'border-green-200',
    icon: '🔬',
    programs: ['B.Sc. (Microbiology)', 'M.Sc. (Microbiology)'],
    hod: 'Dr. [Name]',
    about: 'The Microbiology department offers study of microorganisms and their applications in medicine, agriculture, food science, and industry. With advanced laboratory infrastructure, students engage in rigorous practical training.',
    labs: ['Bacteriology Lab', 'Immunology Lab', 'Industrial Microbiology Lab'],
    faculty: 6,
  },
  {
    slug: 'biotechnology',
    name: 'Biotechnology',
    color: '#a855f7',
    bg: 'bg-purple-50',
    border: 'border-purple-200',
    icon: '🧬',
    programs: ['B.Sc. (Biotechnology)', 'M.Sc. (Biotechnology)'],
    hod: 'Dr. [Name]',
    about: 'Biotechnology at GICEAS bridges the gap between biological sciences and technology. Students explore genetic engineering, bioinformatics, fermentation technology, and pharmaceutical applications in state-of-the-art labs.',
    labs: ['Molecular Biology Lab', 'Tissue Culture Lab', 'Fermentation Lab'],
    faculty: 5,
  },
  {
    slug: 'environmental-science',
    name: 'Environmental Science',
    color: '#10b981',
    bg: 'bg-emerald-50',
    border: 'border-emerald-200',
    icon: '🌿',
    programs: ['B.Sc. (Environmental Science)', 'M.Sc. (Environmental Science)'],
    hod: 'Dr. [Name]',
    about: 'Environmental Science at GICEAS addresses critical challenges of climate change, pollution, and sustainability. The department equips students with tools for environmental monitoring, policy analysis, and conservation science.',
    labs: ['Environmental Monitoring Lab', 'Soil & Water Analysis Lab'],
    faculty: 4,
  },
  {
    slug: 'chemistry',
    name: 'Chemistry',
    color: '#f97316',
    bg: 'bg-orange-50',
    border: 'border-orange-200',
    icon: '⚗️',
    programs: ['B.Sc. (Chemistry)', 'M.Sc. (Chemistry)'],
    hod: 'Dr. [Name]',
    about: 'The Chemistry Department offers comprehensive programmes covering organic, inorganic, physical, and analytical chemistry. Strong emphasis on lab skills prepares graduates for pharma, research, and industrial careers.',
    labs: ['Organic Chemistry Lab', 'Analytical Lab', 'Physical Chemistry Lab'],
    faculty: 6,
  },
  {
    slug: 'allied',
    name: 'Allied Sciences',
    color: '#0d9488',
    bg: 'bg-teal-50',
    border: 'border-teal-200',
    icon: '🧪',
    programs: ['B.Sc. Foundation', 'Allied Electives'],
    hod: 'Dr. [Name]',
    about: 'The Allied Sciences department provides interdisciplinary foundation courses in mathematics, physics, and statistics that support all science programmes at GICEAS.',
    labs: ['Physics Lab', 'Mathematics Resource Centre'],
    faculty: 5,
  },
]

export const COURSES = [
  { program: 'B.Sc. Computer Science', duration: '3 Years', seats: 60, dept: 'Computer Science', level: 'UG' },
  { program: 'M.Sc. Computer Science', duration: '2 Years', seats: 30, dept: 'Computer Science', level: 'PG' },
  { program: 'BCA', duration: '3 Years', seats: 60, dept: 'Computer Science', level: 'UG' },
  { program: 'MCA', duration: '2 Years', seats: 30, dept: 'Computer Science', level: 'PG' },
  { program: 'B.Sc. Microbiology', duration: '3 Years', seats: 40, dept: 'Microbiology', level: 'UG' },
  { program: 'M.Sc. Microbiology', duration: '2 Years', seats: 20, dept: 'Microbiology', level: 'PG' },
  { program: 'B.Sc. Biotechnology', duration: '3 Years', seats: 40, dept: 'Biotechnology', level: 'UG' },
  { program: 'M.Sc. Biotechnology', duration: '2 Years', seats: 20, dept: 'Biotechnology', level: 'PG' },
  { program: 'B.Sc. Environmental Science', duration: '3 Years', seats: 40, dept: 'Environmental Science', level: 'UG' },
  { program: 'M.Sc. Environmental Science', duration: '2 Years', seats: 20, dept: 'Environmental Science', level: 'PG' },
  { program: 'B.Sc. Chemistry', duration: '3 Years', seats: 40, dept: 'Chemistry', level: 'UG' },
  { program: 'M.Sc. Chemistry', duration: '2 Years', seats: 20, dept: 'Chemistry', level: 'PG' },
]

export const EVENTS = [
  { title: 'World Environment Day – Online Awareness Quiz', date: 'June 5, 2025', category: 'Environment', dept: 'Environmental Science' },
  { title: 'Webinar: Software Engineering – Sectors, Roles & Responsibilities', date: 'May 20, 2025', category: 'Seminar', dept: 'Computer Science' },
  { title: 'Seminar on Creating a Professional Resume', date: 'May 10, 2025', category: 'Career', dept: 'Placement Cell' },
  { title: 'Maitri Setu Community Outreach Activities', date: 'April 2025', category: 'NSS', dept: 'NSS Cell' },
  { title: 'Inter-College Science Exhibition', date: 'March 2025', category: 'Exhibition', dept: 'All Departments' },
  { title: 'Research Paper Presentation Workshop', date: 'February 2025', category: 'Research', dept: 'Research Cell' },
]

export const NEWS = [
  { title: 'Mansi Arora Awarded by Director General NCC Lt. General Gurbirpal Singh', date: 'June 2025', category: 'Achievement' },
  { title: 'Merit List 2026-27 Published – Admissions Open', date: 'June 2026', category: 'Admissions' },
  { title: 'GICEAS Faculty Papers Published in UGC-Listed Journals', date: 'May 2025', category: 'Research' },
  { title: 'MoU Signed with Leading IT Company for Placement Support', date: 'April 2025', category: 'Placement' },
  { title: 'GICEAS Students Win at Gujarat State Science Olympiad', date: 'March 2025', category: 'Achievement' },
]
